/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.UbercarCatalog;
import javax.swing.JOptionPane;
/**
 *
 * @author anjalikakade
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    UbercarCatalog catalog;
    DefaultTableModel model;
    public SearchJPanel(UbercarCatalog catalog) {
        initComponents();
        this.catalog = catalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcarmanuyear = new javax.swing.JTextField();
        lblcarsrno = new javax.swing.JLabel();
        txtcarbrand = new javax.swing.JTextField();
        lblcaravai = new javax.swing.JLabel();
        txtcarmno = new javax.swing.JTextField();
        lblcarbrand = new javax.swing.JLabel();
        txtcaravaicity = new javax.swing.JTextField();
        lblcarmanuyear = new javax.swing.JLabel();
        txtmubyu = new javax.swing.JTextField();
        lblcarmno = new javax.swing.JLabel();
        txtcsno1 = new javax.swing.JTextField();
        lblcaravaicity = new javax.swing.JLabel();
        lblcarseatno = new javax.swing.JLabel();
        lblmubyu = new javax.swing.JLabel();
        txtcaravai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        txtcarsrno = new javax.swing.JTextField();
        lblcsnoto = new javax.swing.JLabel();
        txtcsno2 = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();

        txtcarmanuyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcarmanuyearKeyReleased(evt);
            }
        });

        lblcarsrno.setBackground(new java.awt.Color(0, 0, 0));
        lblcarsrno.setForeground(new java.awt.Color(255, 255, 255));
        lblcarsrno.setText("Cars with serial number:");

        txtcarbrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcarbrandKeyReleased(evt);
            }
        });

        lblcaravai.setBackground(new java.awt.Color(0, 0, 0));
        lblcaravai.setForeground(new java.awt.Color(255, 255, 255));
        lblcaravai.setText("Cars available");

        txtcarmno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcarmnoKeyReleased(evt);
            }
        });

        lblcarbrand.setBackground(new java.awt.Color(0, 0, 0));
        lblcarbrand.setForeground(new java.awt.Color(255, 255, 255));
        lblcarbrand.setText("Cars made by Brand:");

        txtcaravaicity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcaravaicityKeyReleased(evt);
            }
        });

        lblcarmanuyear.setBackground(new java.awt.Color(0, 0, 0));
        lblcarmanuyear.setForeground(new java.awt.Color(255, 255, 255));
        lblcarmanuyear.setText("Cars manufactured in year:");

        txtmubyu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmubyuActionPerformed(evt);
            }
        });
        txtmubyu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmubyuKeyReleased(evt);
            }
        });

        lblcarmno.setBackground(new java.awt.Color(0, 0, 0));
        lblcarmno.setForeground(new java.awt.Color(255, 255, 255));
        lblcarmno.setText("Cars with model number:");

        lblcaravaicity.setBackground(new java.awt.Color(0, 0, 0));
        lblcaravaicity.setForeground(new java.awt.Color(255, 255, 255));
        lblcaravaicity.setText("Cars available in city:");

        lblcarseatno.setBackground(new java.awt.Color(0, 0, 0));
        lblcarseatno.setForeground(new java.awt.Color(255, 255, 255));
        lblcarseatno.setText("Cars with seat count from:");

        lblmubyu.setBackground(new java.awt.Color(0, 0, 0));
        lblmubyu.setForeground(new java.awt.Color(255, 255, 255));
        lblmubyu.setText("All Manufactures used by Uber:");

        txtcaravai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaravaiActionPerformed(evt);
            }
        });
        txtcaravai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcaravaiKeyReleased(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Apple SD Gothic Neo", 3, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Search your ride here!");

        tblSearch.setBackground(new java.awt.Color(51, 51, 51));
        tblSearch.setForeground(new java.awt.Color(255, 255, 255));
        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Serial Number", "Model Number", "Vehicle Insurance", "City", "Manufactured Date", "Seat Count", "Availability", "Maintenance Certificate", "Uber Type", "Entry Date", "Updation Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        txtcarsrno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarsrnoActionPerformed(evt);
            }
        });
        txtcarsrno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarsrnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcarsrnoKeyReleased(evt);
            }
        });

        lblcsnoto.setBackground(new java.awt.Color(0, 0, 0));
        lblcsnoto.setForeground(new java.awt.Color(255, 255, 255));
        lblcsnoto.setText("to");

        btnsearch.setBackground(new java.awt.Color(0, 0, 0));
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblcarsrno))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblmubyu)
                                    .addComponent(lblcarmanuyear)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblcarbrand)
                                        .addComponent(lblcaravai))
                                    .addComponent(lblcarmno)
                                    .addComponent(lblcaravaicity)
                                    .addComponent(lblcarseatno))))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcaravai, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcarsrno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcarbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcarmanuyear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcarmno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcaravaicity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcsno1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcsnoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcsno2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtmubyu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnsearch)))
                .addContainerGap(952, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarsrno)
                    .addComponent(txtcarsrno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcaravai, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcaravai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcarbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarmanuyear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcarmanuyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarmno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcarmno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcaravaicity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcaravaicity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarseatno)
                    .addComponent(txtcsno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcsnoto)
                    .addComponent(txtcsno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmubyu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmubyu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnsearch))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcarmanuyearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarmanuyearKeyReleased
        // TODO add your handling code here:
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        for(int i=0;i<catalog.getCatalog().size();i++){

            if(catalog.getCatalog().get(i).getManufacture().contains(txtcarmanuyear.getText())){

                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity()};
                model.addRow(object);
            }
        }
    }//GEN-LAST:event_txtcarmanuyearKeyReleased

    private void txtcarbrandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarbrandKeyReleased
        // TODO add your handling code here:
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        for(int i=0;i<catalog.getCatalog().size();i++){

            if(catalog.getCatalog().get(i).getCarbrand().contains(txtcarbrand.getText())){

                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity()};
                model.addRow(object);
            }
        }
    }//GEN-LAST:event_txtcarbrandKeyReleased

    private void txtcarmnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarmnoKeyReleased
        // TODO add your handling code here:
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        for(int i=0;i<catalog.getCatalog().size();i++){

            if(catalog.getCatalog().get(i).getModelNumber().contains(txtcarmno.getText())){

                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity()};
                model.addRow(object);
            }
        }
    }//GEN-LAST:event_txtcarmnoKeyReleased

    private void txtcaravaicityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaravaicityKeyReleased
        // TODO add your handling code here:
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        for(int i=0;i<catalog.getCatalog().size();i++){

            if(catalog.getCatalog().get(i).getCity().equalsIgnoreCase(txtcarmno.getText())){

                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity()};
                model.addRow(object);
            }
        }
    }//GEN-LAST:event_txtcaravaicityKeyReleased

    private void txtmubyuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmubyuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmubyuActionPerformed

    private void txtmubyuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmubyuKeyReleased
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        ArrayList<String> list = new ArrayList<String>();
        for(int i=0;i<catalog.getCatalog().size();i++){
            list.add(i, catalog.getCatalog().get(i).getCarbrand());
        }
        ArrayList<String> newlist = removeDuplicates(list);
    }//GEN-LAST:event_txtmubyuKeyReleased
    private ArrayList<String> removeDuplicates(ArrayList<String> list){
        ArrayList<String> newList = new ArrayList<String>();
        for(String element : list){
            if(!newList.contains(element)){
                newList.add(element);
            }
        }
         return newList;
    }

    private void txtcaravaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaravaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaravaiActionPerformed

    private void txtcaravaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaravaiKeyReleased

        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        for(int i=0;i<catalog.getCatalog().size();i++){
            if(catalog.getCatalog().get(i).getMaintenanceCertificate().equalsIgnoreCase(txtcaravai.getText())){

                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity()};
                model.addRow(object);
            }
        }
    }//GEN-LAST:event_txtcaravaiKeyReleased

    private void tblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchMouseClicked

    }//GEN-LAST:event_tblSearchMouseClicked

    private void txtcarsrnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarsrnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarsrnoActionPerformed

    private void txtcarsrnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarsrnoKeyPressed

    }//GEN-LAST:event_txtcarsrnoKeyPressed

    private void txtcarsrnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarsrnoKeyReleased
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        for(int i=0;i<catalog.getCatalog().size();i++){

            if(catalog.getCatalog().get(i).getSerialNumber().equalsIgnoreCase(txtcarsrno.getText())){
                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity(),
                    catalog.getCatalog().get(i).getManufacture(),
                    catalog.getCatalog().get(i).getSeatcount(),
                    catalog.getCatalog().get(i).getMaintenanceCertificate(),
                    catalog.getCatalog().get(i).getAvailable(),
                    catalog.getCatalog().get(i).getUbertype(),
                    catalog.getCatalog().get(i).getFleetcatalogEntrydate(),
                    catalog.getCatalog().get(i).getFleetcatalogUpdatedate(),
                };
                model.addRow(object);
            }
        }
    }//GEN-LAST:event_txtcarsrnoKeyReleased

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        model = (DefaultTableModel)tblSearch.getModel();
        model.setRowCount(0);
        int minimum = Integer.parseInt(txtcsno1.getText());
        int maximum = Integer.parseInt(txtcsno2.getText());
        for(int i=0;i<catalog.getCatalog().size();i++){
            int carSeatCount = (catalog.getCatalog().get(i).getSeatcount());
            if(carSeatCount >=minimum && carSeatCount<= maximum){
                Object[] object={catalog.getCatalog().get(i).getCarbrand(),
                    catalog.getCatalog().get(i).getSerialNumber(),
                    catalog.getCatalog().get(i).getModelNumber(),
                    catalog.getCatalog().get(i).getVehicleInsurance(),
                    catalog.getCatalog().get(i).getCity()};
                model.addRow(object);
            }else{
                JOptionPane.showMessageDialog(this," Seat Count is not in Limit given.");
            }
        }

    }//GEN-LAST:event_btnsearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcaravai;
    private javax.swing.JLabel lblcaravaicity;
    private javax.swing.JLabel lblcarbrand;
    private javax.swing.JLabel lblcarmanuyear;
    private javax.swing.JLabel lblcarmno;
    private javax.swing.JLabel lblcarseatno;
    private javax.swing.JLabel lblcarsrno;
    private javax.swing.JLabel lblcsnoto;
    private javax.swing.JLabel lblmubyu;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtcaravai;
    private javax.swing.JTextField txtcaravaicity;
    private javax.swing.JTextField txtcarbrand;
    private javax.swing.JTextField txtcarmanuyear;
    private javax.swing.JTextField txtcarmno;
    private javax.swing.JTextField txtcarsrno;
    private javax.swing.JTextField txtcsno1;
    private javax.swing.JTextField txtcsno2;
    private javax.swing.JTextField txtmubyu;
    // End of variables declaration//GEN-END:variables
}
